### ISSUE TITLE
配置之后直接render html

### ISSUE THREAD

**Issue by callmedada** [luohuam/LP-ADMIN#2]
![image](https://user-images.githubusercontent.com/17517962/37386875-aa4df7ce-2730-11e8-922c-d992bb72b866.png)

配置之后会直接render html

查了一下文档，应该是PHP版本的问题，请换用PHP5

**Comment by callmedada** [comment]
Update: 换用5.5.35 问题依旧存在

**Comment by luohuam** [comment]
SmsDemo.class.php这个类最下面有一个调用示例，将header这一行注释掉就好了
