### ISSUE TITLE
这个下载到电脑上面，我不知道怎么打开

### ISSUE THREAD

**Issue by kaixinren** [luohuam/LP-ADMIN#4]

**Comment by luohuam** [comment]
你得先配好php环境，其他看我写的readme就好了

**Comment by kaixinren** [comment]
我用的是phpstudy的集成开发环境，我直接把这个项目放到了www的目录下，然后把那个BASE SITE设置为./。然后在浏览器输入http://localhost以后发现不能，这中间有什么问题吗

**Comment by kaixinren** [comment]
我如果把那个BASE SITE改为http://localhost以后或者是baidu也不行
